### ISSUE TITLE
ENOENT: no such file or directory gatsby-plugin-html2amp/gatsby-node.js

### ISSUE THREAD

**Issue by 4F2E4A2E** [tomoyukikashiro/gatsby-plugin-html2amp#46]
Hi there and thank you for this plugin.

I just installed the v1.3.1 of this plugin in gatsby project v2.18.25 and followed the instructions as described [1], but it won't build as this [2] error keeps coming up. The node dependency is installed correctly and exists in the fs.

I did all the tricks I could come up with and as described in many issues around gatsby, like this one [3], but I am still not successful. 

Can you give me any hint on how to solve this?

1: https://www.gatsbyjs.org/packages/gatsby-plugin-html2amp
2: `ENOENT: no such file or directory, open 'async /Users/foo/gatsby-example/node_modules/gatsby-plugin-html2amp/gatsby-node.js'`
3: https://github.com/gatsbyjs/gatsby/issues/10457

**Comment by harshnagoratela** [comment]
Hi,

I am also facing the exact same issue. 
Is there any work around for this to get a successful build?

**Comment by tomoyukikashiro** [comment]
@harshnagoratela @4F2E4A2E Sorry for my late reply...

I fixed this issue at `v1.3.3` so plz update 👍

**Comment by DannyHinshaw** [comment]
I'm running into this same issue on`v1.4.1`. Just made sure cache was clean and it still persists (even nuked lock file and node_modules and did a full reinstall). I also tried using `v1.3.3` and the problem persists there as well.

Here's the output (that file is definitely there where it should be):

```
UNHANDLED REJECTION ENOENT: no such file or directory, open 'async /Users/dannyhinshaw/Desktop/Projects/gatsby-52inc/node_modules/gatsby-plugin-html2amp/gatsby-node.js'



  Error: ENOENT: no such file or directory, open 'async /Users/dannyhinshaw/Desktop/Projects/gatsby-52inc/node_modules/gatsby-plugin-html2amp/gatsby-node.js'
  
  - api-runner-node.js:395 
    [gatsby-52inc]/[gatsby]/dist/utils/api-runner-node.js:395:25
  
  - util.js:16 tryCatcher
    [gatsby-52inc]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:547 Promise._settlePromiseFromHandler
    [gatsby-52inc]/[bluebird]/js/release/promise.js:547:31
  
  - promise.js:604 Promise._settlePromise
    [gatsby-52inc]/[bluebird]/js/release/promise.js:604:18
  
  - promise.js:649 Promise._settlePromise0
    [gatsby-52inc]/[bluebird]/js/release/promise.js:649:10
  
  - promise.js:725 Promise._settlePromises
    [gatsby-52inc]/[bluebird]/js/release/promise.js:725:18
  
  - async.js:93 _drainQueueStep
    [gatsby-52inc]/[bluebird]/js/release/async.js:93:12
  
  - async.js:86 _drainQueue
    [gatsby-52inc]/[bluebird]/js/release/async.js:86:9
  
  - async.js:102 Async._drainQueues
    [gatsby-52inc]/[bluebird]/js/release/async.js:102:5
  
  - async.js:15 Immediate.Async.drainQueues [as _onImmediate]
    [gatsby-52inc]/[bluebird]/js/release/async.js:15:14
  
  - timers.js:456 processImmediate
    internal/timers.js:456:21
```

**Comment by somoy99** [comment]
@DannyHinshaw I'm also having the same issue, any workarounds?
